server:
  port: 8081
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

spring:
  profiles:
    active: datasource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level: debug
