# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.27.92.115:5432/matrix
    username: postgres
    password: postgres2345wert
    # 连接池配置
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
    props:
      worker.id: 1
      max.tolerate.time.difference.milliseconds: 100
  redis:
    host: 120.27.92.115
    port: 6379
    password: redispass
    # spring boot 2.0 默认使用 lettuce
    lettuce:
      pool:
        max-active: 100
        max-idle: 8


#  shardingsphere:
#    datasource:
#      name: ds
#      ds:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: org.postgresql.Driver
#        jdbc-url: jdbc:postgresql://120.27.92.115:5432/matrix
#        username: postgres
#        password: postgres2345wert
#        # 连接池配置
#        minimum-idle: 10
#        maximum-pool-size: 15
#
#    sharding:
#      tables:
#        post_info:
#          key-generator:
#            column: id
#            type: SNOWFLAKE
#      default-key-generator:
#        type: SNOWFLAKE
#        column: id
#        props:
#          worker.id: 1
#          max.tolerate.time.difference.milliseconds: 100
#    props:
#      sql:
#        show: true
