server:
  port: 8081
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

spring:
  profiles:
    active: datasource
  jpa:
    show-sql: true

logging:
  level:
    root: debug
  path: ./log/post
  file: matrix-post.log
