server:
  port: 8081
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

spring:
  profiles:
    include:
      - datasource
    active: dev
  jpa:
    show-sql: true

logging:
  level:
    root: debug
